/* ============================================================
   CHIPSTACK STUDIOS — game registry

   To add a game: append an object to GAMES. It automatically
   appears in the Games grid, the Upcoming list (if its status
   is in-development), the footer, and gets a detail page at
   game.html?slug=<slug>. Art is generated by ART[art]().
   ============================================================ */

const GAMES = [
  {
    slug: "salvage-junkies",
    title: "SALVAGE JUNKIES",
    status: "in-development",
    year: "TBA",
    platforms: ["iOS", "ANDROID"],
    accent: "#ff6b2c",
    art: "salvage",
    tagline: "Dismantle junk. Recover treasure. Build Lowtide's greatest salvage operation.",
    short: "A tactile mobile salvage game about dismantling junk, recovering valuable parts, exploring the strange coastal town of Lowtide, and building your salvage operation.",
    description: [
      "Lowtide is a strange little coastal town where the tide brings in more than driftwood. Wrecked machines, mysterious cargo, and honest-to-goodness treasure wash up on the shore — and someone has to take it all apart.",
      "Salvage Junkies is a tactile salvage simulator built for touch. Pull apart rusted machinery piece by piece, learn what's worth keeping, and turn a rusty scrapyard into a thriving operation. Sell parts, take contracts, upgrade your tools, and slowly uncover why Lowtide's shoreline hides so much weird stuff.",
    ],
    features: [
      { title: "TACTILE DISMANTLING", body: "Every piece of junk is a puzzle. Strip bolts, pry panels, and pull parts by hand." },
      { title: "THE TOWN OF LOWTIDE", body: "Meet the locals, take their contracts, and figure out what the tide keeps bringing in." },
      { title: "BUILD YOUR OPERATION", body: "From a rusty shack to a full salvage yard — tools, workshops, and reputation." },
    ],
  },
  {
    slug: "blackjack-empire",
    title: "BLACKJACK EMPIRE",
    status: "released",
    year: "2025",
    platforms: ["iOS", "ANDROID"],
    accent: "#35c27a",
    art: "blackjack",
    tagline: "Hit. Stand. Build an empire one table at a time.",
    short: "A mobile casino empire-builder centered on blackjack: progression, upgrades, and a bankroll that grows from a folding table to a skyline.",
    description: [
      "Start with a folding table, a borrowed deck, and fifty chips. End with a skyline.",
      "Blackjack Empire pairs tight, satisfying blackjack with a full empire-building progression loop. Win hands, grow your bankroll, buy and upgrade casinos, and climb from backroom games to owning the whole strip. Every table you beat funds the next one you build.",
    ],
    features: [
      { title: "REAL BLACKJACK", body: "Clean, fast, satisfying blackjack — no gimmicks, just great cards." },
      { title: "EMPIRE PROGRESSION", body: "Buy casinos, upgrade floors, and watch your bankroll compound into a skyline." },
      { title: "BUILT FOR SHORT SESSIONS", body: "A hand takes seconds. An empire takes... slightly longer." },
    ],
  },
];

/* ---------- status labels ---------- */

const STATUS_META = {
  "released":       { label: "RELEASED",       cls: "status--released" },
  "in-development": { label: "IN DEVELOPMENT", cls: "status--dev" },
  "announced":      { label: "ANNOUNCED",      cls: "status--dev" },
  "stealth":        { label: "CLASSIFIED",     cls: "status--stealth" },
};

/* ============================================================
   Generative poster art.
   Each returns the inner markup for an <svg viewBox="0 0 800 500">.
   Prefix IDs with `p-${slug}-` to avoid collisions between svgs.
   ============================================================ */

const ART = {

  _frame(game, i, inner) {
    const p = `p-${game.slug}`;
    const num = String(i + 1).padStart(2, "0");
    const A = game.accent;
    return `
      <defs>
        <pattern id="${p}-grid" width="40" height="40" patternUnits="userSpaceOnUse">
          <path d="M40 0H0V40" fill="none" stroke="rgba(255,255,255,.045)" stroke-width="1"/>
        </pattern>
        <pattern id="${p}-haz" width="24" height="24" patternUnits="userSpaceOnUse" patternTransform="rotate(45)">
          <rect width="24" height="24" fill="#0e0f12"/>
          <rect width="12" height="24" fill="${A}"/>
        </pattern>
        <pattern id="${p}-scan" width="4" height="4" patternUnits="userSpaceOnUse">
          <rect width="4" height="1" fill="rgba(0,0,0,.35)"/>
        </pattern>
      </defs>
      <rect width="800" height="500" fill="#0e0f12"/>
      <rect width="800" height="500" fill="url(#${p}-grid)"/>
      <text x="770" y="470" text-anchor="end" font-family="JetBrains Mono, monospace"
            font-size="120" fill="rgba(255,255,255,.05)">${num}</text>
      <text x="26" y="42" font-family="JetBrains Mono, monospace" font-size="13"
            letter-spacing="4" fill="rgba(237,236,230,.4)">FIG.${num} · ${game.art.toUpperCase()}</text>
      ${inner}
      <rect width="800" height="500" fill="url(#${p}-scan)" opacity=".5"/>
      <rect x="1" y="1" width="798" height="498" fill="none" stroke="rgba(255,255,255,.07)" stroke-width="2"/>
    `;
  },

  salvage(game, i) {
    const A = game.accent;
    return this._frame(game, i, `
      <circle cx="640" cy="110" r="210" fill="none" stroke="${A}" stroke-opacity=".22" stroke-width="2"/>
      <circle cx="640" cy="110" r="150" fill="none" stroke="${A}" stroke-opacity=".14" stroke-width="2"/>

      <!-- crane beam + trolley -->
      <rect x="120" y="96" width="460" height="10" fill="${A}"/>
      <rect x="464" y="82" width="32" height="24" fill="#0e0f12" stroke="${A}" stroke-width="3"/>
      <line x1="480" y1="106" x2="480" y2="176" stroke="#edece6" stroke-width="4"/>

      <!-- hook -->
      <circle cx="480" cy="192" r="13" fill="none" stroke="${A}" stroke-width="9"/>
      <path d="M480 205 v38 a40 40 0 1 0 -40 -40" fill="none" stroke="${A}"
            stroke-width="12" stroke-linecap="round"/>

      <!-- junk pile -->
      <rect x="230" y="372" width="150" height="44" rx="4" fill="#23252b" transform="rotate(-4 305 394)"/>
      <rect x="286" y="330" width="98" height="38" rx="4" fill="${A}" opacity=".92" transform="rotate(7 335 349)"/>
      <polygon points="405,372 495,372 452,306" fill="#2b2e35"/>
      <circle cx="545" cy="358" r="30" fill="none" stroke="${A}" stroke-width="9"/>
      <circle cx="545" cy="358" r="12" fill="none" stroke="${A}" stroke-width="4" opacity=".6"/>
      <rect x="468" y="378" width="160" height="40" rx="4" fill="#1b1d22" transform="rotate(2 548 398)"/>
      <rect x="372" y="390" width="60" height="24" rx="3" fill="#3a3d45" transform="rotate(-8 402 402)"/>
      <circle cx="262" cy="350" r="7" fill="${A}" opacity=".7"/>
      <rect x="620" y="392" width="34" height="22" rx="3" fill="#3a3d45" transform="rotate(10 637 403)"/>

      <line x1="160" y1="422" x2="660" y2="422" stroke="#3a3d45" stroke-width="3" stroke-dasharray="16 10"/>

      <!-- hazard band -->
      <g transform="rotate(-18 400 470)">
        <rect x="-200" y="452" width="1200" height="24" fill="url(#p-${game.slug}-haz)" opacity=".85"/>
      </g>
    `);
  },

  blackjack(game, i) {
    const A = game.accent;
    return this._frame(game, i, `
      <circle cx="150" cy="390" r="180" fill="none" stroke="${A}" stroke-opacity=".18" stroke-width="2"/>
      <circle cx="150" cy="390" r="120" fill="none" stroke="${A}" stroke-opacity=".12" stroke-width="2"/>

      <!-- back card -->
      <g transform="rotate(-11 355 265)">
        <rect x="275" y="150" width="160" height="230" rx="14" fill="#0c0d10" stroke="#3a3d45" stroke-width="2"/>
        <rect x="290" y="165" width="130" height="200" rx="8" fill="none" stroke="${A}" stroke-width="2" opacity=".45"/>
        <rect x="325" y="210" width="60" height="60" fill="none" stroke="${A}" stroke-width="2"
              opacity=".45" transform="rotate(45 355 240)"/>
      </g>

      <!-- ace card -->
      <g transform="rotate(8 470 275)">
        <rect x="390" y="160" width="160" height="230" rx="14" fill="#edece6"/>
        <text x="408" y="208" font-family="Changa One, sans-serif" font-size="44" fill="#0b0c0e">A</text>
        <rect x="418" y="216" width="16" height="16" fill="${A}" transform="rotate(45 426 224)"/>
        <rect x="450" y="250" width="42" height="42" fill="${A}" transform="rotate(45 471 271)"/>
      </g>

      <!-- chip stack -->
      <g>
        <circle cx="640" cy="388" r="46" fill="${A}"/>
        <circle cx="640" cy="388" r="46" fill="none" stroke="#0b0c0e" stroke-width="10" stroke-dasharray="16 17"/>
        <circle cx="640" cy="388" r="24" fill="#0b0c0e"/>
        <circle cx="640" cy="366" r="46" fill="${A}" opacity=".9"/>
        <circle cx="640" cy="366" r="46" fill="none" stroke="#0b0c0e" stroke-width="10" stroke-dasharray="16 17"/>
        <circle cx="640" cy="366" r="24" fill="#0b0c0e"/>
        <circle cx="640" cy="344" r="46" fill="${A}"/>
        <circle cx="640" cy="344" r="46" fill="none" stroke="#0b0c0e" stroke-width="10" stroke-dasharray="16 17"/>
        <circle cx="640" cy="344" r="24" fill="#0b0c0e"/>
      </g>

      <!-- stray chip -->
      <g transform="rotate(-18 300 425)">
        <circle cx="300" cy="425" r="36" fill="#edece6"/>
        <circle cx="300" cy="425" r="36" fill="none" stroke="${A}" stroke-width="9" stroke-dasharray="13 12"/>
        <circle cx="300" cy="425" r="18" fill="${A}"/>
      </g>

      <!-- hazard band -->
      <g transform="rotate(-18 400 470)">
        <rect x="-200" y="452" width="1200" height="24" fill="url(#p-${game.slug}-haz)" opacity=".85"/>
      </g>
    `);
  },

  stealth(game, i) {
    return this._frame(game, i, `
      <circle cx="400" cy="250" r="150" fill="none" stroke="#3a3d45" stroke-width="2" stroke-dasharray="10 12"/>
      <circle cx="400" cy="250" r="100" fill="none" stroke="#3a3d45" stroke-width="1.5" opacity=".6"/>
      <line x1="400" y1="80" x2="400" y2="120" stroke="#3a3d45" stroke-width="2"/>
      <line x1="400" y1="380" x2="400" y2="420" stroke="#3a3d45" stroke-width="2"/>
      <line x1="230" y1="250" x2="270" y2="250" stroke="#3a3d45" stroke-width="2"/>
      <line x1="530" y1="250" x2="570" y2="250" stroke="#3a3d45" stroke-width="2"/>
      <text x="400" y="300" text-anchor="middle" font-family="Changa One, sans-serif"
            font-size="150" fill="#2b2e35">?</text>
    `);
  },
};
